apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-b-dependent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/longranger/argocd-healthcheck-poc.git
    targetRevision: HEAD
    path: charts/app-b
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Deploy App B to the default namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
